export const Teams = [
  // "Afghanistan",
  "Australia",
  "Bangladesh",
  "England",
  "India",
  "Ireland",
  // "Kenya",
  "New Zealand",
  "South Africa",
  "Scotland",
  "Sri Lanka",
  "West Indies",
  "Zimbabwe",
];

export const MatchTypes = ["ODI", "T20"];

export const Months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const cityAndVenue = [
  { city: "Sylhet", venue: ["Sylhet"] },
  { city: "Adelaide", venue: ["Adelaide Oval"] },
  { city: "Sheikhupura", venue: ["Sheikhupura Stadium"] },
  { city: "Melbourne", venue: ["Melbourne Cricket Ground"] },
  { city: "Rawalpindi", venue: ["Rawalpindi Cricket Stadium"] },
  { city: "Multan", venue: ["Multan Cricket Stadium"] },
  { city: "Manchester", venue: ["Old Trafford"] },
  { city: "Leeds", venue: ["Headingley"] },
  { city: "Sharjah", venue: ["Sharjah Cricket Stadium"] },
  { city: "Bristol", venue: ["County Ground"] },
  { city: "Auckland", venue: ["Eden Park"] },
  { city: "Port Elizabeth", venue: ["St George's Park"] },
  { city: "Gwalior", venue: ["Captain Roop Singh Stadium"] },
  { city: "Mount Maunganui", venue: ["Bay Oval"] },
  { city: "Gold Coast", venue: ["Kerrydale Oval"] },
  {
    city: "Brisbane",
    venue: ["Brisbane Cricket Ground, Woolloongabba", "Peter Burge Oval"],
  },
  {
    city: "Johannesburg",
    venue: ["New Wanderers Stadium", "The Wanderers Stadium"],
  },
  { city: "Jaipur", venue: ["Sawai Mansingh Stadium"] },
  {
    city: "Perth",
    venue: ["Western Australia Cricket Association Ground", "Perth Stadium"],
  },
  { city: "Fatullah", venue: ["Khan Shaheb Osman Ali Stadium"] },
  {
    city: "Sydney",
    venue: ["Sydney Showground Stadium", "Sydney Cricket Ground"],
  },
  { city: "Lahore", venue: ["Gaddafi Stadium"] },
  { city: "Kolkata", venue: ["Eden Gardens"] },
  { city: "Sind", venue: ["Niaz Stadium, Hyderabad"] },
  { city: "Centurion", venue: ["SuperSport Park"] },
  { city: "Lincoln", venue: ["Bert Sutcliffe Oval"] },
  { city: "Loughborough", venue: ["Haslegrave Ground"] },
  {
    city: "Chandigarh",
    venue: [
      "Punjab Cricket Association IS Bindra Stadium, Mohali",
      "Punjab Cricket Association Stadium, Mohali",
    ],
  },
  { city: "Mirpur", venue: ["Shere Bangla National Stadium"] },
  { city: "Pretoria", venue: ["LC de Villiers Oval"] },
  { city: "Durban", venue: ["Kingsmead"] },
  { city: "Bloemfontein", venue: ["Chevrolet Park"] },
  { city: "Abu Dhabi", venue: ["Sheikh Zayed Stadium"] },
  { city: "Pietermaritzburg", venue: ["City Oval"] },
  { city: "Delhi", venue: ["Feroz Shah Kotla"] },
  { city: "Kuala Lumpur", venue: ["Kinrara Academy Oval"] },
  { city: "Bangkok", venue: ["Asian Institute of Technology Ground"] },
  { city: "Hamilton", venue: ["Seddon Park"] },
  { city: "Napier", venue: ["McLean Park"] },
  { city: "Bulawayo", venue: ["Queens Sports Club"] },
  { city: "Faisalabad", venue: ["Iqbal Stadium"] },
  { city: "King City", venue: ["Maple Leaf North-West Ground"] },
  { city: "Chester-le-Street", venue: ["Riverside Ground"] },
  { city: "Ahmedabad", venue: ["Sardar Patel Stadium, Motera"] },
  { city: "Bangalore", venue: ["M Chinnaswamy Stadium"] },
  {
    city: "Karachi",
    venue: ["National Stadium", "Southend Club Cricket Stadium"],
  },
  { city: "Southampton", venue: ["The Rose Bowl"] },
  {
    city: "Dubai",
    venue: [
      "ICC Academy",
      "Dubai International Cricket Stadium",
      "Dubai Sports City Cricket Stadium",
    ],
  },
  {
    city: "Edinburgh",
    venue: [
      "Grange Cricket Club, Raeburn Place",
      "Grange Cricket Club Ground, Raeburn Place",
    ],
  },
  {
    city: "Colombo",
    venue: [
      "Nondescripts Cricket Club Ground",
      "P Sara Oval",
      "R Premadasa Stadium",
      "Sinhalese Sports Club Ground",
      "Colombo Cricket Club Ground",
    ],
  },
  { city: "Chittagong", venue: ["Zahur Ahmed Chowdhury Stadium"] },
  {
    city: "Dublin",
    venue: [
      "YMCA Cricket Club",
      "Observatory Lane, Rathmines",
      "Clontarf Cricket Club Ground",
      "The Village, Malahide",
    ],
  },
  { city: "Wellington", venue: ["Westpac Stadium", "Basin Reserve"] },
  { city: "Cape Town", venue: ["Newlands"] },
  { city: "St Lucia", venue: ["Beausejour Stadium, Gros Islet"] },
  { city: "Potchefstroom", venue: ["Senwes Park"] },
  { city: "Chennai", venue: ["MA Chidambaram Stadium, Chepauk"] },
  { city: "Nelson", venue: ["Saxton Oval"] },
  { city: "Christchurch", venue: ["Hagley Oval", "AMI Stadium"] },
  { city: "Guyana", venue: ["Providence Stadium"] },
  { city: "Grenada", venue: ["National Cricket Stadium, St George's"] },
  { city: "Dunedin", venue: ["University Oval"] },
  { city: "Nairobi", venue: ["Gymkhana Club Ground"] },
  { city: "Kanpur", venue: ["Green Park"] },
  { city: "Guwahati", venue: ["Nehru Stadium"] },
  { city: "Jamaica", venue: ["Sabina Park, Kingston"] },
  { city: "Peshawar", venue: ["Arbab Niaz Stadium"] },
  { city: "St Vincent", venue: ["Arnos Vale Ground, Kingstown"] },
  { city: "Doha", venue: ["West End Park International Cricket Stadium"] },
  { city: "Canberra", venue: ["Manuka Oval"] },
  { city: "Leicester", venue: ["Grace Road"] },
  {
    city: "Taunton",
    venue: ["County Ground", "The Cooper Associates County Ground"],
  },
  { city: "Birmingham", venue: ["Edgbaston"] },
  { city: "Worcester", venue: ["County Ground, New Road"] },
  { city: "Benoni", venue: ["Willowmoore Park"] },
  { city: "Nottingham", venue: ["Trent Bridge"] },
  { city: "London", venue: ["Kennington Oval", "Lord's"] },
  { city: "Derby", venue: ["County Ground"] },
  { city: "Cardiff", venue: ["Sophia Gardens"] },
  {
    city: "Hambantota",
    venue: ["Mahinda Rajapaksa International Cricket Stadium, Sooriyawewa"],
  },
  { city: "Trinidad", venue: ["Queen's Park Oval, Port of Spain"] },
  { city: "Barbados", venue: ["Kensington Oval, Bridgetown"] },
  { city: "Chelmsford", venue: ["County Ground"] },
];
