export const Teams = [
  "Afghanistan",
  "Australia",
  "Bangladesh",
  "England",
  "India",
  "Ireland",
  "Kenya",
  "New Zealand",
  "South Africa",
  "Scotland",
  "Sri Lanka",
  "West Indies",
  "Zimbabwe",
  "Pakistan",
];
export const TeamsPakistan = [
  "Afghanistan",
  "Australia",
  "Bangladesh",
  "England",
  "India",
  "Ireland",
  "Kenya",
  "New Zealand",
  "South Africa",
  "Scotland",
  "Sri Lanka",
  "West Indies",
  "Zimbabwe",
  "Pakistan",
];

export const MatchTypes = ["ODI", "T20"];

export const Months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const Venue = [
  "AMI Stadium",
  "Adelaide Oval",
  "Affies Park",
  "Al Amerat Cricket Ground Oman Cricket (Ministry Turf 1)",
  "Andhra Cricket Association-Visakhapatnam District Cricket Association Stadium",
  "Antigua Recreation Ground, St John's",
  "Arbab Niaz Stadium",
  "Arnos Vale Ground, Kingstown",
  "Arun Jaitley Stadium",
  "Barabati Stadium",
  "Barsapara Cricket Stadium",
  "Basin Reserve",
  "Bay Oval",
  "Beausejour Stadium, Gros Islet",
  "Bellerive Oval",
  "Bert Sutcliffe Oval",
  "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium",
  "Boland Park",
  "Brabourne Stadium",
  "Bready Cricket Club, Magheramason",
  "Brisbane Cricket Ground, Woolloongabba",
  "Buffalo Park",
  "Bulawayo Athletic Club",
  "Cambusdoon New Ground",
  "Captain Roop Singh Stadium",
  "Castle Avenue",
  "Central Broward Regional Park Stadium Turf Ground",
  "Chevrolet Park",
  "Chittagong Divisional Stadium",
  "Civil Service Cricket Club, Stormont",
  "Clontarf Cricket Club Ground",
  "Cobham Oval (New)",
  "County Ground",
  "Darren Sammy National Cricket Stadium, Gros Islet",
  "Darren Sammy National Cricket Stadium, St Lucia",
  "De Beers Diamond Oval",
  "Diamond Oval",
  "Docklands Stadium",
  "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium",
  "Dubai International Cricket Stadium",
  "Dubai Sports City Cricket Stadium",
  "Eden Gardens",
  "Eden Park",
  "Edgbaston",
  "Feroz Shah Kotla",
  "Gaddafi Stadium",
  "Galle International Stadium",
  "Goodyear Park",
  "Grange Cricket Club Ground, Raeburn Place",
  "Grange Cricket Club, Raeburn Place",
  "Greater Noida Sports Complex Ground",
  "Green Park",
  "Greenfield International Stadium",
  "Gymkhana Club Ground",
  "Hagley Oval",
  "Harare Sports Club",
  "Headingley",
  "Himachal Pradesh Cricket Association Stadium",
  "Holkar Cricket Stadium",
  "ICC Academy",
  "ICC Global Cricket Academy",
  "Indian Petrochemicals Corporation Limited Sports Complex Ground",
  "Iqbal Stadium",
  "JSCA International Stadium Complex",
  "Jade Stadium",
  "Jaffery Sports Club Ground",
  "Keenan Stadium",
  "Kennington Oval",
  "Kensington Oval, Barbados",
  "Kensington Oval, Bridgetown",
  "Khan Shaheb Osman Ali Stadium",
  "Kingsmead",
  "Kinrara Academy Oval",
  "Lord's",
  "M Chinnaswamy Stadium",
  "M.Chinnaswamy Stadium",
  "MA Chidambaram Stadium, Chepauk",
  "Madhavrao Scindia Cricket Ground",
  "Maharani Usharaje Trust Cricket Ground",
  "Maharashtra Cricket Association Stadium",
  "Mahinda Rajapaksa International Cricket Stadium, Sooriyawewa",
  "Malahide",
  "Mangaung Oval",
  "Mannofield Park",
  "Manuka Oval",
  "Maple Leaf North-West Ground",
  "Marrara Cricket Ground",
  "McLean Park",
  "Melbourne Cricket Ground",
  "Mission Road Ground, Mong Kok",
  "Mombasa Sports Club Ground",
  "Multan Cricket Stadium",
  "Nahar Singh Stadium",
  "Narayanganj Osmani Stadium",
  "National Cricket Stadium, Grenada",
  "National Cricket Stadium, St George's",
  "National Stadium",
  "Nehru Stadium",
  "Nehru Stadium, Fatorda",
  "New Wanderers Stadium",
  "Newlands",
  "Niaz Stadium, Hyderabad",
  "OUTsurance Oval",
  "Old Hararians",
  "Old Trafford",
  "P Saravanamuttu Stadium",
  "Pallekele International Cricket Stadium",
  "Perth Stadium",
  "Providence Stadium",
  "Punjab Cricket Association IS Bindra Stadium, Mohali",
  "Punjab Cricket Association Stadium, Mohali",
  "Queen's Park Oval, Port of Spain",
  "Queen's Park Oval, Trinidad",
  "Queens Sports Club",
  "Queenstown Events Centre",
  "R Premadasa Stadium",
  "R.Premadasa Stadium, Khettarama",
  "Rajiv Gandhi International Cricket Stadium, Dehradun",
  "Rajiv Gandhi International Stadium, Uppal",
  "Rangiri Dambulla International Stadium",
  "Rawalpindi Cricket Stadium",
  "Reliance Stadium",
  "Riverside Ground",
  "Ruaraka Sports Club Ground",
  "Sabina Park, Kingston",
  "Sardar Patel Stadium, Motera",
  "Saurashtra Cricket Association Stadium",
  "Sawai Mansingh Stadium",
  "Saxton Oval",
  "Sector 16 Stadium",
  "Seddon Park",
  "Sedgars Park",
  "Senwes Park",
  "Shaheed Chandu Stadium",
  "Sharjah Cricket Association Stadium",
  "Sharjah Cricket Stadium",
  "Sheikh Abu Naser Stadium",
  "Sheikh Zayed Stadium",
  "Sheikhupura Stadium",
  "Shere Bangla National Stadium",
  "Shere Bangla National Stadium, Mirpur",
  "Sinhalese Sports Club Ground",
  "Sir Vivian Richards Stadium, North Sound",
  "Sophia Gardens",
  "Sportpark Het Schootsveld",
  "St George's Park",
  "SuperSport Park",
  "Sydney Cricket Ground",
  "Sylhet International Cricket Stadium",
  "The Cooper Associates County Ground",
  "The Rose Bowl",
  "The Village, Malahide",
  "The Wanderers Stadium",
  "Titwood",
  "Toronto Cricket",
  "Trent Bridge",
  "Tribhuvan University International Cricket Ground",
  "University Oval",
  "VRA Ground",
  "Vidarbha Cricket Association Ground",
  "Vidarbha Cricket Association Stadium, Jamtha",
  "Wanderers Cricket Ground",
  "Wankhede Stadium",
  "Warner Park, Basseterre",
  "Western Australia Cricket Association Ground",
  "Westpac Stadium",
  "Willowmoore Park",
  "Windsor Park, Roseau",
  "Zahur Ahmed Chowdhury Stadium",
  "Zohur Ahmed Chowdhury Stadium",
];

export const cityAndVenue = [
  // { city: "Sylhet", venue: ["Sylhet"] },
  // { city: "Adelaide", venue: ["Adelaide Oval"] },
  // { city: "Sheikhupura", venue: ["Sheikhupura Stadium"] },
  // { city: "Melbourne", venue: ["Melbourne Cricket Ground"] },
  // { city: "Rawalpindi", venue: ["Rawalpindi Cricket Stadium"] },
  // { city: "Multan", venue: ["Multan Cricket Stadium"] },
  { city: "Manchester", venue: ["Old Trafford"] },
  { city: "Leeds", venue: ["Headingley"] },
  { city: "Sharjah", venue: ["Sharjah Cricket Stadium"] },
  { city: "Bristol", venue: ["County Ground"] },
  { city: "Auckland", venue: ["Eden Park"] },
  { city: "Port Elizabeth", venue: ["St George's Park"] },
  // { city: "Gwalior", venue: ["Captain Roop Singh Stadium"] },
  // { city: "Mount Maunganui", venue: ["Bay Oval"] },
  // { city: "Gold Coast", venue: ["Kerrydale Oval"] },
  {
    city: "Brisbane",
    venue: ["Brisbane Cricket Ground, Woolloongabba", "Peter Burge Oval"],
  },
  {
    city: "Johannesburg",
    venue: ["New Wanderers Stadium", "The Wanderers Stadium"],
  },
  { city: "Jaipur", venue: ["Sawai Mansingh Stadium"] },
  {
    city: "Perth",
    venue: ["Western Australia Cricket Association Ground", "Perth Stadium"],
  },
  { city: "Fatullah", venue: ["Khan Shaheb Osman Ali Stadium"] },
  {
    city: "Sydney",
    venue: ["Sydney Showground Stadium", "Sydney Cricket Ground"],
  },
  { city: "Lahore", venue: ["Gaddafi Stadium"] },
  { city: "Kolkata", venue: ["Eden Gardens"] },
  { city: "Sind", venue: ["Niaz Stadium, Hyderabad"] },
  { city: "Centurion", venue: ["SuperSport Park"] },
  { city: "Lincoln", venue: ["Bert Sutcliffe Oval"] },
  // { city: "Loughborough", venue: ["Haslegrave Ground"] },
  {
    city: "Chandigarh",
    venue: [
      "Punjab Cricket Association IS Bindra Stadium, Mohali",
      "Punjab Cricket Association Stadium, Mohali",
    ],
  },
  // { city: "Mirpur", venue: ["Shere Bangla National Stadium"] },
  // { city: "Pretoria", venue: ["LC de Villiers Oval"] },
  // { city: "Durban", venue: ["Kingsmead"] },
  // { city: "Bloemfontein", venue: ["Chevrolet Park"] },
  { city: "Abu Dhabi", venue: ["Sheikh Zayed Stadium"] },
  // { city: "Pietermaritzburg", venue: ["City Oval"] },
  { city: "Delhi", venue: ["Feroz Shah Kotla"] },
  // { city: "Kuala Lumpur", venue: ["Kinrara Academy Oval"] },
  // { city: "Bangkok", venue: ["Asian Institute of Technology Ground"] },
  // { city: "Hamilton", venue: ["Seddon Park"] },
  // { city: "Napier", venue: ["McLean Park"] },
  // { city: "Bulawayo", venue: ["Queens Sports Club"] },
  // { city: "Faisalabad", venue: ["Iqbal Stadium"] },
  // { city: "King City", venue: ["Maple Leaf North-West Ground"] },
  // { city: "Chester-le-Street", venue: ["Riverside Ground"] },
  { city: "Ahmedabad", venue: ["Sardar Patel Stadium, Motera"] },
  { city: "Bangalore", venue: ["M Chinnaswamy Stadium"] },
  {
    city: "Karachi",
    venue: ["National Stadium", "Southend Club Cricket Stadium"],
  },
  { city: "Southampton", venue: ["The Rose Bowl"] },
  {
    city: "Dubai",
    venue: [
      "ICC Academy",
      "Dubai International Cricket Stadium",
      "Dubai Sports City Cricket Stadium",
    ],
  },
  {
    city: "Edinburgh",
    venue: [
      "Grange Cricket Club, Raeburn Place",
      "Grange Cricket Club Ground, Raeburn Place",
    ],
  },
  {
    city: "Colombo",
    venue: [
      "Nondescripts Cricket Club Ground",
      "P Sara Oval",
      "R Premadasa Stadium",
      "Sinhalese Sports Club Ground",
      "Colombo Cricket Club Ground",
    ],
  },
  // { city: "Chittagong", venue: ["Zahur Ahmed Chowdhury Stadium"] },
  {
    city: "Dublin",
    venue: [
      "YMCA Cricket Club",
      "Observatory Lane, Rathmines",
      "Clontarf Cricket Club Ground",
      "The Village, Malahide",
    ],
  },
  // { city: "Wellington", venue: ["Westpac Stadium", "Basin Reserve"] },
  { city: "Cape Town", venue: ["Newlands"] },
  // { city: "St Lucia", venue: ["Beausejour Stadium, Gros Islet"] },
  // { city: "Potchefstroom", venue: ["Senwes Park"] },
  { city: "Chennai", venue: ["MA Chidambaram Stadium, Chepauk"] },
  // { city: "Nelson", venue: ["Saxton Oval"] },
  // { city: "Christchurch", venue: ["Hagley Oval", "AMI Stadium"] },
  // { city: "Guyana", venue: ["Providence Stadium"] },
  // { city: "Grenada", venue: ["National Cricket Stadium, St George's"] },
  // { city: "Dunedin", venue: ["University Oval"] },
  // { city: "Nairobi", venue: ["Gymkhana Club Ground"] },
  // { city: "Kanpur", venue: ["Green Park"] },
  // { city: "Guwahati", venue: ["Nehru Stadium"] },
  // { city: "Jamaica", venue: ["Sabina Park, Kingston"] },
  // { city: "Peshawar", venue: ["Arbab Niaz Stadium"] },
  // { city: "St Vincent", venue: ["Arnos Vale Ground, Kingstown"] },
  // { city: "Doha", venue: ["West End Park International Cricket Stadium"] },
  // { city: "Canberra", venue: ["Manuka Oval"] },
  // { city: "Leicester", venue: ["Grace Road"] },
  // {
  //   city: "Taunton",
  //   venue: ["County Ground", "The Cooper Associates County Ground"],
  // },
  { city: "Birmingham", venue: ["Edgbaston"] },
  // { city: "Worcester", venue: ["County Ground, New Road"] },
  // { city: "Benoni", venue: ["Willowmoore Park"] },
  { city: "Nottingham", venue: ["Trent Bridge"] },
  { city: "London", venue: ["Kennington Oval", "Lord's"] },
  { city: "Derby", venue: ["County Ground"] },
  { city: "Cardiff", venue: ["Sophia Gardens"] },
  // {
  //   city: "Hambantota",
  //   venue: ["Mahinda Rajapaksa International Cricket Stadium, Sooriyawewa"],
  // },
  // { city: "Trinidad", venue: ["Queen's Park Oval, Port of Spain"] },
  // { city: "Barbados", venue: ["Kensington Oval, Bridgetown"] },
  // { city: "Chelmsford", venue: ["County Ground"] },
];
