export const Teams = [
  "Afghanistan",
  // "Africa XI",
  // "Asia XI",
  "Australia",
  "Bangladesh",
  "Bermuda",
  "Canada",
  "England",
  "Hong Kong",
  "India",
  "Ireland",
  "Kenya",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Oman",
  "Pakistan",
  "Papua New Guinea",
  "Scotland",
  "South Africa",
  "Sri Lanka",
  "United Arab Emirates",
  "United States of America",
  "West Indies",
  "Zimbabwe",
];

export const TeamsPakistan = [
  "Afghanistan",
  "Australia",
  "Bangladesh",
  "England",
  "India",
  "Ireland",
  "Kenya",
  "New Zealand",
  "South Africa",
  "Scotland",
  "Sri Lanka",
  "West Indies",
  "Zimbabwe",
  "Pakistan",
];

export const MatchTypes = ["ODI", "T20"];

export const Months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const VENUE_ODI = [
  "Mahinda Rajapaksa International Cricket Stadium, Sooriyawewa",
  "Hagley Oval",
  "Madhavrao Scindia Cricket Ground",
  "Kennington Oval",
  "MA Chidambaram Stadium, Chepauk",
  "Trent Bridge",
  "Old Trafford",
  "Willowmoore Park",
  "Melbourne Cricket Ground",
  "Kingsmead",
  "Pallekele International Cricket Stadium",
  "Gymkhana Club Ground",
  "Punjab Cricket Association Stadium, Mohali",
  "Harare Sports Club",
  "Rangiri Dambulla International Stadium",
  "Mannofield Park",
  "Sabina Park, Kingston",
  "Headingley",
  "Zahur Ahmed Chowdhury Stadium",
  "National Stadium",
  "Brabourne Stadium",
  "Queens Sports Club",
  "Sir Vivian Richards Stadium, North Sound",
  "Civil Service Cricket Club, Stormont",
  "ICC Academy",
  "Brisbane Cricket Ground, Woolloongabba",
  "McLean Park",
  "Marrara Cricket Ground",
  "Adelaide Oval",
  "New Wanderers Stadium",
  "AMI Stadium",
  "Sydney Cricket Ground",
  "Maple Leaf North-West Ground",
  "Green Park",
  "R.Premadasa Stadium, Khettarama",
  "R Premadasa Stadium",
  "Warner Park, Basseterre",
  "Dubai International Cricket Stadium",
  "Bay Oval",
  "Saxton Oval",
  "Bellerive Oval",
  "Sharjah Cricket Stadium",
  "Darren Sammy National Cricket Stadium, Gros Islet",
  "Toronto Cricket",
  "Vidarbha Cricket Association Stadium, Jamtha",
  "ICC Global Cricket Academy",
  "Docklands Stadium",
  "Feroz Shah Kotla",
  "Edgbaston",
  "St George's Park",
  "Al Amerat Cricket Ground Oman Cricket (Ministry Turf 1)",
  "Holkar Cricket Stadium",
  "Shere Bangla National Stadium",
  "The Rose Bowl",
  "SuperSport Park",
  "Sylhet International Cricket Stadium",
  "Reliance Stadium",
  "Central Broward Regional Park Stadium Turf Ground",
  "Kensington Oval, Bridgetown",
  "Sardar Patel Stadium, Motera",
  "Multan Cricket Stadium",
  "County Ground",
  "Sheikh Zayed Stadium",
  "Diamond Oval",
  "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium",
  "Western Australia Cricket Association Ground",
  "Westpac Stadium",
  "Seddon Park",
  "Punjab Cricket Association IS Bindra Stadium, Mohali",
  "Nehru Stadium",
  "Providence Stadium",
  "The Wanderers Stadium",
  "Sophia Gardens",
  "Basin Reserve",
  "Queen's Park Oval, Port of Spain",
  "Eden Park",
  "Arnos Vale Ground, Kingstown",
  "Khan Shaheb Osman Ali Stadium",
  "Mangaung Oval",
  "Maharani Usharaje Trust Cricket Ground",
  "Kinrara Academy Oval",
  "Lord's",
  "Shere Bangla National Stadium, Mirpur",
  "Buffalo Park",
  "The Village, Malahide",
  "Tribhuvan University International Cricket Ground",
  "Newlands",
  "Queenstown Events Centre",
  "Rajiv Gandhi International Cricket Stadium, Dehradun",
  "Barabati Stadium",
  "Eden Gardens",
  "Riverside Ground",
  "National Cricket Stadium, St George's",
  "Bulawayo Athletic Club",
  "Sheikh Abu Naser Stadium",
  "Malahide",
  "Greater Noida Sports Complex Ground",
  "M Chinnaswamy Stadium",
  "Grange Cricket Club Ground, Raeburn Place",
  "Chevrolet Park",
  "Indian Petrochemicals Corporation Limited Sports Complex Ground",
  "Senwes Park",
  "Sportpark Het Schootsveld",
  "Chittagong Divisional Stadium",
  "Cambusdoon New Ground",
  "Zohur Ahmed Chowdhury Stadium",
  "JSCA International Stadium Complex",
  "Gaddafi Stadium",
  "Rajiv Gandhi International Stadium, Uppal",
  "Mombasa Sports Club Ground",
  "Sawai Mansingh Stadium",
  "Iqbal Stadium",
  "University Oval",
  "VRA Ground",
  "Wankhede Stadium",
  "Windsor Park, Roseau",
  "Nehru Stadium, Fatorda",
  "Shaheed Chandu Stadium",
  "Sharjah Cricket Association Stadium",
  "Beausejour Stadium, Gros Islet",
  "Andhra Cricket Association-Visakhapatnam District Cricket Association Stadium",
  "Himachal Pradesh Cricket Association Stadium",
  "Vidarbha Cricket Association Ground",
  "Mission Road Ground, Mong Kok",
  "Dubai Sports City Cricket Stadium",
  "Narayanganj Osmani Stadium",
  "Kensington Oval, Barbados",
  "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium",
  "Sinhalese Sports Club Ground",
  "De Beers Diamond Oval",
  "Maharashtra Cricket Association Stadium",
  "Manuka Oval",
  "Saurashtra Cricket Association Stadium",
  "Rawalpindi Cricket Stadium",
  "Jaffery Sports Club Ground",
  "Ruaraka Sports Club Ground",
  "Sheikhupura Stadium",
  "Goodyear Park",
  "Clontarf Cricket Club Ground",
  "Grange Cricket Club, Raeburn Place",
  "Captain Roop Singh Stadium",
  "Old Hararians",
  "M.Chinnaswamy Stadium",
  "Queen's Park Oval, Trinidad",
  "Boland Park",
  "Bready Cricket Club, Magheramason",
  "Bert Sutcliffe Oval",
  "Antigua Recreation Ground, St John's",
  "Darren Sammy National Cricket Stadium, St Lucia",
  "Jade Stadium",
  "Barsapara Cricket Stadium",
  "Perth Stadium",
  "Titwood",
  "Greenfield International Stadium",
  "Sedgars Park",
  "National Cricket Stadium, Grenada",
  "Sector 16 Stadium",
  "Affies Park",
  "Galle International Stadium",
  "Wanderers Cricket Ground",
  "The Cooper Associates County Ground",
  "P Saravanamuttu Stadium",
  "Castle Avenue",
  "Keenan Stadium",
  "Nahar Singh Stadium",
  "Arun Jaitley Stadium",
  "OUTsurance Oval",
  "Cobham Oval (New)",
  "Arbab Niaz Stadium",
  "Niaz Stadium, Hyderabad",
];

export const VENUE_T20 = [
  "Central Broward Regional Park Stadium Turf Ground",
  "Beausejour Stadium, Gros Islet",
  "M Chinnaswamy Stadium",
  "Trent Bridge",
  "Dubai International Cricket Stadium",
  "ICC Academy",
  "Westpac Stadium",
  "Harare Sports Club",
  "Kingsmead",
  "Punjab Cricket Association IS Bindra Stadium, Mohali",
  "Sharjah Cricket Stadium",
  "R Premadasa Stadium",
  "Kinrara Academy Oval",
  "The Rose Bowl",
  "Sheikh Zayed Stadium",
  "Melbourne Cricket Ground",
  "Kennington Oval",
  "Rawalpindi Cricket Stadium",
  "Queen's Park Oval, Port of Spain",
  "Sylhet Stadium",
  "Indian Association Ground",
  "Shere Bangla National Stadium, Mirpur",
  "Amini Park",
  "Shere Bangla National Stadium",
  "Saurashtra Cricket Association Stadium",
  "Eden Park",
  "The Wanderers Stadium",
  "Maharashtra Cricket Association Stadium",
  "Eden Gardens",
  "Tolerance Oval",
  "Civil Service Cricket Club, Stormont",
  "Vidarbha Cricket Association Stadium, Jamtha",
  "County Ground",
  "Green Park",
  "Sydney Cricket Ground",
  "Mombasa Sports Club Ground",
  "ICC Global Cricket Academy",
  "Zahur Ahmed Chowdhury Stadium",
  "The Village, Malahide",
  "La Manga Club Bottom Ground",
  "Pallekele International Cricket Stadium",
  "Gymkhana Club Ground",
  "Bready Cricket Club, Magheramason",
  "Hazelaarweg",
  "Rajiv Gandhi International Cricket Stadium",
  "Newlands",
  "Senwes Park",
  "Al Amerat Cricket Ground Oman Cricket (Ministry Turf 1)",
  "Pierre Werner Cricket Ground",
  "Wanderers Cricket Ground",
  "Tribhuvan University International Cricket Ground",
  "Sportpark Westvliet",
  "VRA Ground",
  "National Cricket Stadium, Grenada",
  "Lord's",
  "Rajiv Gandhi International Stadium, Uppal",
  "Kensington Oval, Bridgetown",
  "Wankhede Stadium",
  "Stadium Australia",
  "New Wanderers Stadium",
  "Gaddafi Stadium",
  "National Stadium",
  "Sophia Gardens",
  "Hagley Oval",
  "Arnos Vale Ground, Kingstown",
  "Mission Road Ground, Mong Kok",
  "MA Chidambaram Stadium, Chepauk",
  "Providence Stadium",
  "Old Trafford",
  "JSCA International Stadium Complex",
  "Greenfield International Stadium",
  "Sheikh Abu Naser Stadium",
  "Adelaide Oval",
  "OUTsurance Oval",
  "Arun Jaitley Stadium",
  "Grange Cricket Club Ground, Raeburn Place",
  "King George V Sports Ground",
  "Bellerive Oval",
  "Punjab Cricket Association Stadium, Mohali",
  "Riverside Ground",
  "White Hill Field, Sandys Parish",
  "Warner Park, Basseterre",
  "Mahinda Rajapaksa International Cricket Stadium, Sooriyawewa",
  "McLean Park",
  "ICC Academy Ground No 2",
  "St George's Park",
  "Seddon Park",
  "Khan Shaheb Osman Ali Stadium",
  "Terdthai Cricket Ground",
  "Western Australia Cricket Association Ground",
  "M.Chinnaswamy Stadium",
  "Kyambogo Cricket Oval",
  "Barabati Stadium",
  "Darren Sammy National Cricket Stadium, St Lucia",
  "Brisbane Cricket Ground, Woolloongabba",
  "SuperSport Park",
  "Feroz Shah Kotla",
  "Queens Sports Club",
  "Grange Cricket Club, Raeburn Place",
  "Sportpark Het Schootsveld",
  "R.Premadasa Stadium, Khettarama",
  "Edgbaston",
  "Desert Springs Cricket Ground",
  "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium",
  "Perth Stadium",
  "AMI Stadium",
  "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium",
  "Bay Oval",
  "United Cricket Club Ground",
  "College Field",
  "Moara Vlasiei Cricket Ground",
  "Sir Vivian Richards Stadium, North Sound",
  "Bermuda National Stadium",
  "Tony Ireland Stadium",
  "Himachal Pradesh Cricket Association Stadium",
  "P Sara Oval",
  "Sabina Park, Kingston",
  "Greater Noida Sports Complex Ground",
  "Carrara Oval",
  "Buffalo Park",
  "Manuka Oval",
  "Boland Park",
  "Subrata Roy Sahara Stadium",
  "Simonds Stadium, South Geelong",
  "Al Amerat Cricket Ground Oman Cricket (Ministry Turf 2)",
  "Lugogo Cricket Oval",
  "Rajiv Gandhi International Cricket Stadium, Dehradun",
  "Sportpark Maarschalkerweerd",
  "Warner Park, St Kitts",
  "Jade Stadium",
  "Bready",
  "Windsor Park, Roseau",
  "Holkar Cricket Stadium",
  "Moses Mabhida Stadium",
  "Sardar Patel Stadium, Motera",
  "Mangaung Oval",
  "Maple Leaf North-West Ground",
  "Providence Stadium, Guyana",
  "Saxton Oval",
  "Barsapara Cricket Stadium",
  "De Beers Diamond Oval",
  "Sylhet International Cricket Stadium",
  "Clontarf Cricket Club Ground",
  "Brabourne Stadium",
];

export const T20_TEAMS = [
  "West Indies",
  "India",
  "Australia",
  "England",
  "South Africa",
  "Netherlands",
  "Afghanistan",
  "Papua New Guinea",
  "New Zealand",
  "United Arab Emirates",
  "Pakistan",
  "Zimbabwe",
  "Kenya",
  // "Malaysia",
  // "Vanuatu",
  "Ireland",
  "Sri Lanka",
  // "Nigeria",
  // "Singapore",
  "Scotland",
  "Namibia",
  "Nepal",
  // "Qatar",
  "Bangladesh",
  "Hong Kong",
  "Oman",
  // "United States of America",
  // "Thailand",
  // "Maldives",
  "Canada",
  // "Jersey",
  // "Spain",
  // "Portugal",
  // "Belgium",
  // "Luxembourg",
  // "Bhutan",
  // "Kuwait",
  // "Czech Republic",
  // "Gibraltar",
  // "ICC World XI",
  // "Denmark",
  // "Italy",
  "Bermuda",
  // "Cayman Islands",
  // "Norway",
  // "Philippines",
  // "Ghana",
  // "Guernsey",
  // "Uganda",
  // "Bahrain",
  // "Germany",
  // "Botswana",
  // "Romania",
  // "Bulgaria",
  // "Saudi Arabia",
  // "Isle of Man",
  // "Iran",
];

export const ODI_TEAMS = [
  "Sri Lanka",
  "New Zealand",
  "England",
  "India",
  "West Indies",
  // "Africa XI",
  // "Asia XI",
  "South Africa",
  "Australia",
  "Scotland",
  "Canada",
  "Zimbabwe",
  "Kenya",
  "Pakistan",
  "Netherlands",
  "Ireland",
  "Bangladesh",
  "Afghanistan",
  "United Arab Emirates",
  "Nepal",
  "Oman",
  "Papua New Guinea",
  // "United States of America",
  "Bermuda",
  "Namibia",
  "Hong Kong",
];

export const cityAndVenue = [
  // { city: "Sylhet", venue: ["Sylhet"] },
  // { city: "Adelaide", venue: ["Adelaide Oval"] },
  // { city: "Sheikhupura", venue: ["Sheikhupura Stadium"] },
  // { city: "Melbourne", venue: ["Melbourne Cricket Ground"] },
  // { city: "Rawalpindi", venue: ["Rawalpindi Cricket Stadium"] },
  // { city: "Multan", venue: ["Multan Cricket Stadium"] },
  { city: "Manchester", venue: ["Old Trafford"] },
  { city: "Leeds", venue: ["Headingley"] },
  { city: "Sharjah", venue: ["Sharjah Cricket Stadium"] },
  { city: "Bristol", venue: ["County Ground"] },
  { city: "Auckland", venue: ["Eden Park"] },
  { city: "Port Elizabeth", venue: ["St George's Park"] },
  // { city: "Gwalior", venue: ["Captain Roop Singh Stadium"] },
  // { city: "Mount Maunganui", venue: ["Bay Oval"] },
  // { city: "Gold Coast", venue: ["Kerrydale Oval"] },
  {
    city: "Brisbane",
    venue: ["Brisbane Cricket Ground, Woolloongabba", "Peter Burge Oval"],
  },
  {
    city: "Johannesburg",
    venue: ["New Wanderers Stadium", "The Wanderers Stadium"],
  },
  { city: "Jaipur", venue: ["Sawai Mansingh Stadium"] },
  {
    city: "Perth",
    venue: ["Western Australia Cricket Association Ground", "Perth Stadium"],
  },
  { city: "Fatullah", venue: ["Khan Shaheb Osman Ali Stadium"] },
  {
    city: "Sydney",
    venue: ["Sydney Showground Stadium", "Sydney Cricket Ground"],
  },
  { city: "Lahore", venue: ["Gaddafi Stadium"] },
  { city: "Kolkata", venue: ["Eden Gardens"] },
  { city: "Sind", venue: ["Niaz Stadium, Hyderabad"] },
  { city: "Centurion", venue: ["SuperSport Park"] },
  { city: "Lincoln", venue: ["Bert Sutcliffe Oval"] },
  // { city: "Loughborough", venue: ["Haslegrave Ground"] },
  {
    city: "Chandigarh",
    venue: [
      "Punjab Cricket Association IS Bindra Stadium, Mohali",
      "Punjab Cricket Association Stadium, Mohali",
    ],
  },
  // { city: "Mirpur", venue: ["Shere Bangla National Stadium"] },
  // { city: "Pretoria", venue: ["LC de Villiers Oval"] },
  // { city: "Durban", venue: ["Kingsmead"] },
  // { city: "Bloemfontein", venue: ["Chevrolet Park"] },
  { city: "Abu Dhabi", venue: ["Sheikh Zayed Stadium"] },
  // { city: "Pietermaritzburg", venue: ["City Oval"] },
  { city: "Delhi", venue: ["Feroz Shah Kotla"] },
  // { city: "Kuala Lumpur", venue: ["Kinrara Academy Oval"] },
  // { city: "Bangkok", venue: ["Asian Institute of Technology Ground"] },
  // { city: "Hamilton", venue: ["Seddon Park"] },
  // { city: "Napier", venue: ["McLean Park"] },
  // { city: "Bulawayo", venue: ["Queens Sports Club"] },
  // { city: "Faisalabad", venue: ["Iqbal Stadium"] },
  // { city: "King City", venue: ["Maple Leaf North-West Ground"] },
  // { city: "Chester-le-Street", venue: ["Riverside Ground"] },
  { city: "Ahmedabad", venue: ["Sardar Patel Stadium, Motera"] },
  { city: "Bangalore", venue: ["M Chinnaswamy Stadium"] },
  {
    city: "Karachi",
    venue: ["National Stadium", "Southend Club Cricket Stadium"],
  },
  { city: "Southampton", venue: ["The Rose Bowl"] },
  {
    city: "Dubai",
    venue: [
      "ICC Academy",
      "Dubai International Cricket Stadium",
      "Dubai Sports City Cricket Stadium",
    ],
  },
  {
    city: "Edinburgh",
    venue: [
      "Grange Cricket Club, Raeburn Place",
      "Grange Cricket Club Ground, Raeburn Place",
    ],
  },
  {
    city: "Colombo",
    venue: [
      "Nondescripts Cricket Club Ground",
      "P Sara Oval",
      "R Premadasa Stadium",
      "Sinhalese Sports Club Ground",
      "Colombo Cricket Club Ground",
    ],
  },
  // { city: "Chittagong", venue: ["Zahur Ahmed Chowdhury Stadium"] },
  {
    city: "Dublin",
    venue: [
      "YMCA Cricket Club",
      "Observatory Lane, Rathmines",
      "Clontarf Cricket Club Ground",
      "The Village, Malahide",
    ],
  },
  // { city: "Wellington", venue: ["Westpac Stadium", "Basin Reserve"] },
  { city: "Cape Town", venue: ["Newlands"] },
  // { city: "St Lucia", venue: ["Beausejour Stadium, Gros Islet"] },
  // { city: "Potchefstroom", venue: ["Senwes Park"] },
  { city: "Chennai", venue: ["MA Chidambaram Stadium, Chepauk"] },
  // { city: "Nelson", venue: ["Saxton Oval"] },
  // { city: "Christchurch", venue: ["Hagley Oval", "AMI Stadium"] },
  // { city: "Guyana", venue: ["Providence Stadium"] },
  // { city: "Grenada", venue: ["National Cricket Stadium, St George's"] },
  // { city: "Dunedin", venue: ["University Oval"] },
  // { city: "Nairobi", venue: ["Gymkhana Club Ground"] },
  // { city: "Kanpur", venue: ["Green Park"] },
  // { city: "Guwahati", venue: ["Nehru Stadium"] },
  // { city: "Jamaica", venue: ["Sabina Park, Kingston"] },
  // { city: "Peshawar", venue: ["Arbab Niaz Stadium"] },
  // { city: "St Vincent", venue: ["Arnos Vale Ground, Kingstown"] },
  // { city: "Doha", venue: ["West End Park International Cricket Stadium"] },
  // { city: "Canberra", venue: ["Manuka Oval"] },
  // { city: "Leicester", venue: ["Grace Road"] },
  // {
  //   city: "Taunton",
  //   venue: ["County Ground", "The Cooper Associates County Ground"],
  // },
  { city: "Birmingham", venue: ["Edgbaston"] },
  // { city: "Worcester", venue: ["County Ground, New Road"] },
  // { city: "Benoni", venue: ["Willowmoore Park"] },
  { city: "Nottingham", venue: ["Trent Bridge"] },
  { city: "London", venue: ["Kennington Oval", "Lord's"] },
  { city: "Derby", venue: ["County Ground"] },
  { city: "Cardiff", venue: ["Sophia Gardens"] },
  // {
  //   city: "Hambantota",
  //   venue: ["Mahinda Rajapaksa International Cricket Stadium, Sooriyawewa"],
  // },
  // { city: "Trinidad", venue: ["Queen's Park Oval, Port of Spain"] },
  // { city: "Barbados", venue: ["Kensington Oval, Bridgetown"] },
  // { city: "Chelmsford", venue: ["County Ground"] },
];
